name: Unit Tests (act-rules)
on:
  pull_request:
    branches:
      - develop
    paths:
      - packages/act-rules
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup (cache, dependencies)
        uses: ./.github/actions/install_and_cache_dependencies

      - name: Build
        run: npm -ws run build

      - name: Test
        run: npm -w @qualweb/act-rules test