name: "@qualweb/act-rules"
on:
  pull_request:
    branches:
      - develop
    paths:
      - "packages/act-rules/**"
  workflow_call:

jobs:
  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      # Setup/prelims
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup (cache, dependencies)
        uses: ./.github/actions/install_and_cache_dependencies

      # Build all packages. This ensures that everything this package depends on
      # has also been built.
      - name: Build
        run: npm -ws run build

      # Run unit tests on this package, and its dependents.

      - name: "@qualweb/act-rules"
        # TODO: consider a more tailored test call here, that only calls affected
        # act rules if they can be accurately determined. Full suite can take 20
        # minutes on a beefy system, hours on a basic CI/CD VM. Being able to just
        # run tests for affected ACT rules could bring that down considerably.
        run: npm -w @qualweb/act-rules test
      
      - name: "Test dependents"
        run: npm run $(npx ts-node scripts/get_dependents.ts --as-workspaces --include-self @qualweb/act-rules) test
