name: "@qualweb/locale"
on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "packages/locale/**"

jobs:
  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      # Setup/prelims
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup (cache, dependencies)
        uses: ./.github/actions/install_and_cache_dependencies

      # Build all packages. This ensures that everything this package depends on
      # has also been built.
      - name: Build
        run: npm -ws run build

      - name: "Unit tests for this package"
        run: npm -w @qualweb/locale test

      - name: "Test dependents"
        run: npm run $(npx ts-node scripts/get_dependents.ts --as-workspaces @qualweb/locale) test