# This workflow file contains a workflow that will ONLY run unit tests for
# packages which have seen changes.
name: Unit tests
on:
  push:
    branches:
      - main
      - develop
  workflow_call:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      # Setup/prelims
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup (cache, dependencies)
        uses: ./.github/actions/install_and_cache_dependencies

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40

      - name: Output changed files
        run: echo ${{ steps.changed-files.outputs.modified_files }}

      # Build all packages. Do this AFTER the changed files check. After we
      # build everything, a lot of things may look changed to the changed-files
      # action.
      - name: Build
        run: npm -ws run build

      - name: "@qualweb/act-rules"
        if: contains(steps.changed-files.outputs.modified_files, 'packages/act-rules')
        run: npm -w @qualweb/act-rules test

      - name: "@qualweb/best-practices"
        if: contains(steps.changed-files.outputs.modified_files, 'packages/best-practices')
        run: npm -w @qualweb/best-practices test

      - name: "@qualweb/cli"
        if: contains(steps.changed-files.outputs.modified_files, 'packages/cli')
        run: npm -w @qualweb/cli test

      - name: "@qualweb/core"
        if: contains(steps.changed-files.outputs.modified_files, 'packages/core')
        run: npm -w @qualweb/core test

      - name: "@qualweb/counter"
        if: contains(steps.changed-files.outputs.modified_files, 'packages/counter')
        run: npm -w @qualweb/counter test

      - name: "@qualweb/crawler"
        if: contains(steps.changed-files.outputs.modified_files, 'packages/crawler')
        run: npm -w @qualweb/crawler test

      - name: "@qualweb/dom"
        if: contains(steps.changed-files.outputs.modified_files, 'packages/dom')
        run: npm -w @qualweb/dom test

      - name: "@qualweb/earl-reporter"
        if: contains(steps.changed-files.outputs.modified_files, 'packages/earl-reporter')
        run: npm -w @qualweb/earl-reporter test

      - name: "@qualweb/evaluation"
        if: contains(steps.changed-files.outputs.modified_files, 'packages/evaluation')
        run: npm -w @qualweb/evaluation test

      - name: "@qualweb/locale"
        if: contains(steps.changed-files.outputs.modified_files, 'packages/locale')
        run: npm -w @qualweb/locale test

      - name: "@qualweb/qw-element"
        if: contains(steps.changed-files.outputs.modified_files, 'packages/qw-element')
        run: npm -w @qualweb/qw-element test

      - name: "@qualweb/qw-page"
        if: contains(steps.changed-files.outputs.modified_files, 'packages/qw-page')
        run: npm -w @qualweb/qw-page test

      - name: "@qualweb/util"
        if: contains(steps.changed-files.outputs.modified_files, 'packages/util')
        run: npm -w @qualweb/util test

      - name: "@qualweb/wcag-techniques"
        if: contains(steps.changed-files.outputs.modified_files, 'packages/wcag-techniques')
        run: npm -w @qualweb/wcag-techniques test