# This workflow file contains a workflow that will ONLY run unit tests for
# packages which have seen changes.
name: Unit tests
on:
  push:
    branches:
      - main
      - develop
  workflow_call:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      # Setup/prelims
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup (cache, dependencies)
        uses: ./.github/actions/install_and_cache_dependencies

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40

      - name: Output changed files
        run: echo ${{ steps.changed-files.outputs.modified_files }}

      # Build all packages. Do this AFTER the changed files check. After we
      # build everything, a lot of things may look changed to the changed-files
      # action.
      - name: Build
        run: npm -ws run build

      - name: "@qualweb/act-rules"
        if: contains(steps.changed-files.outputs.modified_files, 'packages/act-rules')
        run: npm -w @qualweb/act-rules test

      - name: "@qualweb/best-practices"
        if: contains(steps.changed-files.outputs.modified_files, 'packages/best-practices')
        run: npm -w @qualweb/best-practices test

      - name: "@qualweb/cli"
        if: contains(steps.changed-files.outputs.modified_files, 'packages/cli')
        run: npm -w @qualweb/cli test

      - name: "@qualweb/core"
        if: contains(steps.changed-files.outputs.modified_files, 'packages/core')
        run: npm -w @qualweb/core test